# Generated by Django 5.1.4 on 2025-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Caption", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captionhistory",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
